# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0003_parameter_deployment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametertype",
            name="value",
            field=models.CharField(
                choices=[("FIX", "Fixed"), ("DYN", "Dynamic"), ("FOR", "From a form")],
                max_length=50,
                verbose_name="how the value should be determined",
            ),
        ),
    ]
