# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-30 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0004_auto_20200530_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametertype",
            name="on_instance",
            field=models.BooleanField(
                default=True,
                help_text="This is relevant if this parameter is dynamic. If not checked the parameter's value will be a list of the field value aggregated over all the model instances.",
                verbose_name="Fetch value for a specific instance.",
            ),
        ),
    ]
