# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-30 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0005_parametertype_on_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametertype",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="This must be filled for dynamic parameters.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
                verbose_name="Model name",
            ),
        ),
        migrations.AlterField(
            model_name="parametertype",
            name="dynamic_field",
            field=models.CharField(
                blank=True,
                help_text="Field name that is to be fetched, this must be filled for dynamic parameters.",
                max_length=255,
                null=True,
                verbose_name="Field name.",
            ),
        ),
    ]
